### ISSUE TITLE
ssh tunnel into the database instance

### ISSUE THREAD

**Issue by monkeypants** [gs-gs/codepublican-taiga#1]
as discussed @ml019, we (OOP project) need to query the taiga database.

this ticket can be closed when we (@ltankey and @monkeypants) have the ability to ssh tunnel into postgres:
 * IP address of the jump box / bastion server
 * ssh access to the jump box (keys, etc)
 * route from the bastion server to the rds service

So we can tunnel into the server and run queries.

**Comment by monkeypants** [comment]
assigning Rolly and Mike, but please feel free to delegate to @kshychko etc, no need for consierge service :)

**Comment by roleyfoley** [comment]
ssh instance started and details provided to @monkeypants and @ltankey

**Comment by monkeypants** [comment]
woot!
