### ISSUE TITLE
performance issue / attacks of the stuck

### ISSUE THREAD

**Issue by monkeypants** [gs-gs/codepublican-taiga#2]
the current deployment suffers from attacks of the stuck.

problem is - taiga stops responding (spa freezes). If page reload when frozen, get stuck with mostly white screen. When frozen, seems to be frozen for all users simultaneously.

when frozen and refreshing, in "developer tools" browser extension, the stuck seems to be on websocket connection

there are two connections that take a minute before the browser gives up; i forget the urls but one of them definitely has the word "websocket" in it.

**Comment by monkeypants** [comment]
Of course, it's working perfectly now so I can't make screen shots...

**Comment by roleyfoley** [comment]
Closing as codepublican-taiga is no longer maintained
